import Metal
import MetalSprockets
import MetalSprocketsExampleShaders
import MetalSprocketsSupport
import simd

// Element is like SwiftUI View but for Metal
struct DemoCubeRenderPipeline: Element {
    let shaderLibrary: ShaderLibrary
    let transform: float4x4
    let time: Float

    init(transform: float4x4, time: Float) throws {
        // ShaderLibrary generated by @ShaderLibrary macro - type-safe access to .metal shaders
        self.shaderLibrary = try ShaderLibrary(bundle: .metalSprocketsExampleShaders())
        self.transform = transform
        self.time = time
    }

    var body: some Element {
        get throws {
            // RenderPipeline binds shaders and configures pipeline state
            try RenderPipeline(label: "Demo Cube", vertexShader: shaderLibrary.vertexMain, fragmentShader: shaderLibrary.fragmentMain) {
                let vertices = generateCubeVertices()
                Draw { encoder in
                    encoder.drawPrimitives(primitiveType: .triangle, vertexStart: 0, vertexCount: vertices.count)
                }
                .vertexValues(vertices, index: 0)
                .parameter("transform", value: transform)
                .parameter("time", value: time)
            }
            // Tells Metal how to interpret Vertex struct
            .vertexDescriptor(Vertex.descriptor)
            .depthCompare(function: .less, enabled: true)
        }
    }
}
