import Metal
import MetalSprocketsExampleShaders
import MetalSprockets
import MetalSprocketsSupport
import simd

// Element is like SwiftUI View but for Metal
struct DemoCubeRenderPipeline: Element {
    let shaderLibrary: ShaderLibrary
    let transform: float4x4
    let time: Float

    init(transform: float4x4, time: Float) throws {
        // ShaderLibrary generated by @ShaderLibrary macro - type-safe access to .metal shaders
        self.shaderLibrary = try ShaderLibrary(bundle: .metalSprocketsExampleShaders())
        self.transform = transform
        self.time = time
    }

    var body: some Element {
        get throws {
            // RenderPipeline binds shaders and configures pipeline state
            try RenderPipeline(label: "Demo Cube", vertexShader: shaderLibrary.vertexMain, fragmentShader: shaderLibrary.fragmentMain) {
                // Draw gives direct access to MTLRenderCommandEncoder
                Draw { encoder in
                    var transform = transform
                    encoder.setVertexBytes(&transform, length: MemoryLayout<float4x4>.stride, index: 1)

                    var time = time
                    encoder.setFragmentBytes(&time, length: MemoryLayout<Float>.stride, index: 0)

                    var vertices = generateCubeVertices()
                    encoder.setVertexBytes(&vertices, length: MemoryLayout<Vertex>.stride * vertices.count, index: 0)
                    encoder.drawPrimitives(type: .triangle, vertexStart: 0, vertexCount: vertices.count)
                }
            }
            // Tells Metal how to interpret Vertex struct
            .vertexDescriptor(Vertex.descriptor)
            .depthCompare(function: .less, enabled: true)
        }
    }
}
